sudo: required
services:
  - docker
language: generic

before_install:
  - cd ./frontend
  - docker build -t fluzzykitten/docker-react -f ./Dockerfile.dev .

before_build:
  - cd ./frontend
  - ls -lart
  - docker build -t fluzzykitten/docker-react -f ./Dockerfile.dev .

script:
  - docker run -e CI=true USERNAME/docker-react npm run test