sudo: required
services:
  - docker
language: generic

before_install:
  - docker build -t fluzzykitten/docker-test -f ./complex/client/Dockerfile.dev ./complex/client

script:
  - docker run -e CI=true fluzzykitten/docker-test npm run test -- --coverage

after_success:
  - docker build -t fluzzykitten/multi-client ./complex/client ./complex/client
  - docker build -t fluzzykitten/multi-nginx ./complex/nginx ./complex/nginx
  - docker build -t fluzzykitten/multi-server ./complex/server ./complex/server
  - docker build -t fluzzykitten/multi-worker ./complex/worker ./complex/worker

#log into docker CLI
  - echo "DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
#push images
  - docker push fluzzykitten/multi-client
  - docker push fluzzykitten/multi-nginx
  - docker push fluzzykitten/multi-server
  - docker push fluzzykitten/multi-worker

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "react-web"
  env: "ReactWeb-env-1"
  bucket_name: "elasticbeanstalk-us-east-2-165372868605"
  bucket_path: "react-web"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY